CREATE TABLE `sessions` (
	id VARCHAR(128) PRIMARY KEY,
	data MEDIUMTEXT NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	expires_at TIMESTAMP NOT NULL,
	INDEX idx_expires_at (expires_at)
);